version: '3.8'

services:
  ui:
    build:
      context: .
      dockerfile: DOCKERFILE
    ports:
      - "8501:8501"
    volumes:
      - ./results:/app/results
      - ./conversations:/app/conversations
    environment:
      - OLLAMA_HOST=ollama:11434
    depends_on:
      - ollama
  
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"

volumes:
  ollama_data:

